from .create_event import *
from .homepage_view import *
from .log_in_view import *
from .log_out_view import *
from .signup_view import *
from .main_page_view import *
from .dashboard import  *
from .completed_events import *
from .statistics import *
from .clear_schedule import *
from .event_detail_view import *
from .delete_event import *
from .edit_event import *
from .event_instances import *
from .user_details import *
from .smart_planner_view import *
from .get_schedules import *
from .get_events_api import *
